version: '3.3'
services:
    tacplus:
        container_name: tacplus
        build:
            context: .
        volumes:
            - './tacplus.cfg:/etc/tacacs+/tac_plus.conf'
        ports:
            - 49:49
        tty: true
